### ISSUE TITLE
Where is  MoleculePreprocessorExtended? 

### ISSUE THREAD

**Issue by PatWalters** [anya-chen/RingSystems#1]
Hi,

Your preprocessing scripts all include the line 

from cheminformatics import MoleculePreprocessorExtended

Where does the cheminformatics library come from?  This doesn't seem to be in the installation requirements. 

Thanks

**Comment by anya-chen** [comment]
Thank you for pointing out. The cheminformatic library is a library we used in our lab. I now added the modules  used in this project under Preprocessing/src/ and changed import accordingly.

**Comment by PatWalters** [comment]
Thanks!
